info:
  name: Delete a rule configuration
  type: http
  seq: 8

http:
  method: DELETE
  url: "{{baseUrl}}/v1alpha/projects/:projectId/regions/:region/rules/:name"
  params:
    - name: projectId
      value: ""
      type: path
    - name: region
      value: ""
      type: path
    - name: name
      value: ""
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: To delete a rule configuration this endpoint is used, but it is only possible to delete it if no WAF configuration is referencing it.
