info:
  name: List all configured regions in a network area.
  type: http
  seq: 13

http:
  method: GET
  url: "{{baseUrl}}/v2beta1/organizations/:organizationId/network-areas/:areaId/regions"
  params:
    - name: organizationId
      value: d61a8564-c8dd-4ffb-bc15-143e7d0c85ed
      type: path
      description: The identifier (ID) of a STACKIT Organization.
    - name: areaId
      value: d61a8564-c8dd-4ffb-bc15-143e7d0c85ed
      type: path
      description: The identifier (ID) of a STACKIT Network Area.
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: Get a list of all configured regions.
