info:
  name: Create a kubeconfig
  type: http
  seq: 7

http:
  method: POST
  url: "{{baseUrl}}/v1/projects/:projectId/clusters/:clusterName/kubeconfig"
  params:
    - name: projectId
      value: ""
      type: path
    - name: clusterName
      value: ""
      type: path
  body:
    type: json
    data: |-
      {
        "expirationSeconds": ""
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: Create a new kubeconfig for the cluster. You can specify the expiration (in seconds) in the request body. Its value must be in the range from 600 (10 min) to 15552000 (6 months).
