info:
  name: get-kubeconfig-by-instance-id
  type: http
  seq: 8

http:
  method: GET
  url: "{{baseUrl}}/v1beta1/projects/:projectId/regions/:regionId/instances/:instanceId/kubeconfig"
  params:
    - name: projectId
      value: ""
      type: path
      description: The STACKIT portal project UUID the instance is part of.
    - name: regionId
      value: eu01
      type: path
      description: The STACKIT region the instance is part of.
    - name: regionId
      value: eu02
      type: path
      description: The STACKIT region the instance is part of.
      disabled: true
    - name: instanceId
      value: ""
      type: path
      description: The full ID of the instance, <display_name>-<project_hash>.
    - name: expirationSeconds
      value: "3600"
      type: query
      description: Expiration of the included token in seconds
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: Returns the kubeconfig for the given instance.
