info:
  name: CreateAlertConfigRoute
  type: http
  seq: 16

http:
  method: POST
  url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/alertconfigs/routes"
  params:
    - name: instanceId
      value: ""
      type: path
    - name: projectId
      value: ""
      type: path
  body:
    type: json
    data: |-
      {
        "continue": false,
        "groupBy": [],
        "groupInterval": "",
        "groupWait": "",
        "match": {},
        "matchRe": {},
        "matchers": [],
        "receiver": "",
        "repeatInterval": "",
        "routes": [
          {
            "continue": false,
            "groupBy": [],
            "groupInterval": "",
            "groupWait": "",
            "match": {},
            "matchRe": {},
            "matchers": [],
            "receiver": "",
            "repeatInterval": "",
            "routes": [
              {}
            ]
          }
        ]
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 202 Response
    description: Create alert config route.
    request:
      url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/alertconfigs/routes"
      method: POST
      params:
        - name: instanceId
          value: ""
          type: path
        - name: projectId
          value: ""
          type: path
      body:
        type: json
        data: |-
          {
            "continue": false,
            "groupBy": [],
            "groupInterval": "",
            "groupWait": "",
            "match": {},
            "matchRe": {},
            "matchers": [],
            "receiver": "",
            "repeatInterval": "",
            "routes": [
              {
                "continue": false,
                "groupBy": [],
                "groupInterval": "",
                "groupWait": "",
                "match": {},
                "matchRe": {},
                "matchers": [],
                "receiver": "",
                "repeatInterval": "",
                "routes": [
                  {}
                ]
              }
            ]
          }
    response:
      status: 202
      statusText: Accepted
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "data": {
              "groupBy": [
                "alertname",
                "cluster",
                "service"
              ],
              "groupInterval": "5m",
              "groupWait": "30s",
              "receiver": "team-X-mails",
              "repeatInterval": "3h",
              "routes": [
                {
                  "matchRe": {
                    "service": "^(foo1|foo2|baz)$"
                  },
                  "receiver": "team-X-paper"
                },
                {
                  "match": {
                    "service": "files"
                  },
                  "receiver": "team-X-pager"
                }
              ]
            },
            "message": "Success"
          }
  - name: 400 Response
    description: Something went wrong.
    request:
      url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/alertconfigs/routes"
      method: POST
      params:
        - name: instanceId
          value: ""
          type: path
        - name: projectId
          value: ""
          type: path
      body:
        type: json
        data: |-
          {
            "continue": false,
            "groupBy": [],
            "groupInterval": "",
            "groupWait": "",
            "match": {},
            "matchRe": {},
            "matchers": [],
            "receiver": "",
            "repeatInterval": "",
            "routes": [
              {
                "continue": false,
                "groupBy": [],
                "groupInterval": "",
                "groupWait": "",
                "match": {},
                "matchRe": {},
                "matchers": [],
                "receiver": "",
                "repeatInterval": "",
                "routes": [
                  {}
                ]
              }
            ]
          }
    response:
      status: 400
      statusText: Bad Request
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "message": "Something went wrong"
          }
  - name: 403 Response
    description: You are not authorized
    request:
      url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/alertconfigs/routes"
      method: POST
      params:
        - name: instanceId
          value: ""
          type: path
        - name: projectId
          value: ""
          type: path
      body:
        type: json
        data: |-
          {
            "continue": false,
            "groupBy": [],
            "groupInterval": "",
            "groupWait": "",
            "match": {},
            "matchRe": {},
            "matchers": [],
            "receiver": "",
            "repeatInterval": "",
            "routes": [
              {
                "continue": false,
                "groupBy": [],
                "groupInterval": "",
                "groupWait": "",
                "match": {},
                "matchRe": {},
                "matchers": [],
                "receiver": "",
                "repeatInterval": "",
                "routes": [
                  {}
                ]
              }
            ]
          }
    response:
      status: 403
      statusText: Forbidden
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "detail": "You do not have permission to perform this action."
          }

docs: Create alert config route in routes of route.
