info:
  name: DeleteAlertConfigReceiver
  type: http
  seq: 12

http:
  method: DELETE
  url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/alertconfigs/receivers/:receiver"
  params:
    - name: instanceId
      value: ""
      type: path
    - name: projectId
      value: ""
      type: path
    - name: receiver
      value: ""
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 202 Response
    description: Delete alert config receiver.
    request:
      url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/alertconfigs/receivers/:receiver"
      method: DELETE
      params:
        - name: instanceId
          value: ""
          type: path
        - name: projectId
          value: ""
          type: path
        - name: receiver
          value: ""
          type: path
    response:
      status: 202
      statusText: Accepted
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "data": [
              {
                "emailConfigs": [
                  {
                    "to": "team-X+alerts@example.org"
                  }
                ],
                "name": "team-X-mails"
              },
              {
                "emailConfigs": [
                  {
                    "to": "team-X+papers@example.org"
                  }
                ],
                "name": "team-X-paper"
              },
              {
                "emailConfigs": [
                  {
                    "to": "team-Y+paper@example.org"
                  }
                ],
                "name": "team-Y-paper"
              },
              {
                "emailConfigs": [
                  {
                    "to": "team-X+alerts-critical@example.org"
                  }
                ],
                "name": "team-X-pager",
                "opsgenieConfigs": [
                  {
                    "apiKey": "12345678",
                    "apiUrl": "https://example.opsgenie.org"
                  }
                ]
              }
            ],
            "message": "Success"
          }
  - name: 403 Response
    description: You are not authorized
    request:
      url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/alertconfigs/receivers/:receiver"
      method: DELETE
      params:
        - name: instanceId
          value: ""
          type: path
        - name: projectId
          value: ""
          type: path
        - name: receiver
          value: ""
          type: path
    response:
      status: 403
      statusText: Forbidden
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "detail": "You do not have permission to perform this action."
          }
  - name: 404 Response
    description: Alert config receiver not found.
    request:
      url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/alertconfigs/receivers/:receiver"
      method: DELETE
      params:
        - name: instanceId
          value: ""
          type: path
        - name: projectId
          value: ""
          type: path
        - name: receiver
          value: ""
          type: path
    response:
      status: 404
      statusText: Not Found
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "message": "Alert config receiver not found."
          }

docs: Delete alert config receiver.
