info:
  name: DeleteScrapeConfigs
  type: http
  seq: 96

http:
  method: DELETE
  url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/scrapeconfigs"
  params:
    - name: instanceId
      value: ""
      type: path
    - name: projectId
      value: ""
      type: path
    - name: jobName
      value: "[]"
      type: query
      description: Name of the jobs that should be deleted
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 202 Response
    description: Deleted scrape configs.
    request:
      url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/scrapeconfigs"
      method: DELETE
      params:
        - name: instanceId
          value: ""
          type: path
        - name: projectId
          value: ""
          type: path
        - name: jobName
          value: "[]"
          type: query
          description: Name of the jobs that should be deleted
    response:
      status: 202
      statusText: Accepted
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "data": [
              {
                "jobName": "test",
                "metricsPath": "/metrics",
                "scheme": "https",
                "scrapeInterval": "5m",
                "scrapeTimeout": "1m",
                "staticConfigs": [
                  {
                    "targets": [
                      "example.com"
                    ]
                  }
                ]
              }
            ],
            "message": "Scrape configs successfully deleted"
          }
  - name: 403 Response
    description: You are not authorized
    request:
      url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/scrapeconfigs"
      method: DELETE
      params:
        - name: instanceId
          value: ""
          type: path
        - name: projectId
          value: ""
          type: path
        - name: jobName
          value: "[]"
          type: query
          description: Name of the jobs that should be deleted
    response:
      status: 403
      statusText: Forbidden
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "detail": "You do not have permission to perform this action."
          }

docs: Delete scrape configs.
