info:
  name: DeleteScrapeConfigs
  type: http
  seq: 96

http:
  method: DELETE
  url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/scrapeconfigs"
  params:
    - name: instanceId
      value: ""
      type: path
    - name: projectId
      value: ""
      type: path
    - name: jobName
      value: "[]"
      type: query
      description: Name of the jobs that should be deleted
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: Delete scrape configs.
