info:
  name: GetScrapeConfig
  type: http
  seq: 101

http:
  method: GET
  url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/scrapeconfigs/:jobName"
  params:
    - name: instanceId
      value: ""
      type: path
    - name: jobName
      value: ""
      type: path
    - name: projectId
      value: ""
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: Get scrape target.
    request:
      url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/scrapeconfigs/:jobName"
      method: GET
      params:
        - name: instanceId
          value: ""
          type: path
        - name: jobName
          value: ""
          type: path
        - name: projectId
          value: ""
          type: path
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "data": {
              "jobName": "test",
              "metricsPath": "/metrics",
              "scheme": "https",
              "scrapeInterval": "5m",
              "scrapeTimeout": "1m",
              "staticConfigs": [
                {
                  "targets": [
                    "example.com"
                  ]
                }
              ]
            },
            "message": "Successfully got scrape target"
          }
  - name: 403 Response
    description: You are not authorized
    request:
      url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/scrapeconfigs/:jobName"
      method: GET
      params:
        - name: instanceId
          value: ""
          type: path
        - name: jobName
          value: ""
          type: path
        - name: projectId
          value: ""
          type: path
    response:
      status: 403
      statusText: Forbidden
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "detail": "You do not have permission to perform this action."
          }

docs: Get scrape config.
