info:
  name: UpdateScrapeConfig
  type: http
  seq: 102

http:
  method: PUT
  url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/scrapeconfigs/:jobName"
  params:
    - name: instanceId
      value: ""
      type: path
    - name: jobName
      value: ""
      type: path
    - name: projectId
      value: ""
      type: path
  body:
    type: json
    data: |-
      {
        "basicAuth": {
          "password": "",
          "username": ""
        },
        "bearerToken": "",
        "honorLabels": false,
        "honorTimeStamps": false,
        "metricsPath": "",
        "metricsRelabelConfigs": [
          {
            "action": "replace",
            "modulus": 0,
            "regex": "",
            "replacement": "",
            "separator": "",
            "sourceLabels": [],
            "targetLabel": ""
          }
        ],
        "params": {},
        "sampleLimit": 0,
        "scheme": "http",
        "scrapeInterval": "",
        "scrapeTimeout": "",
        "staticConfigs": [
          {
            "labels": {},
            "targets": []
          }
        ],
        "tlsConfig": {
          "insecureSkipVerify": false
        }
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 202 Response
    description: Update scrape target.
    request:
      url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/scrapeconfigs/:jobName"
      method: PUT
      params:
        - name: instanceId
          value: ""
          type: path
        - name: jobName
          value: ""
          type: path
        - name: projectId
          value: ""
          type: path
      body:
        type: json
        data: |-
          {
            "basicAuth": {
              "password": "",
              "username": ""
            },
            "bearerToken": "",
            "honorLabels": false,
            "honorTimeStamps": false,
            "metricsPath": "",
            "metricsRelabelConfigs": [
              {
                "action": "replace",
                "modulus": 0,
                "regex": "",
                "replacement": "",
                "separator": "",
                "sourceLabels": [],
                "targetLabel": ""
              }
            ],
            "params": {},
            "sampleLimit": 0,
            "scheme": "http",
            "scrapeInterval": "",
            "scrapeTimeout": "",
            "staticConfigs": [
              {
                "labels": {},
                "targets": []
              }
            ],
            "tlsConfig": {
              "insecureSkipVerify": false
            }
          }
    response:
      status: 202
      statusText: Accepted
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "data": [
              {
                "jobName": "test",
                "metricsPath": "/metrics",
                "scheme": "https",
                "scrapeInterval": "5m",
                "scrapeTimeout": "1m",
                "staticConfigs": [
                  {
                    "targets": [
                      "example.com"
                    ]
                  }
                ]
              }
            ],
            "message": "Successfully updated scrape target"
          }
  - name: 400 Response
    description: Something went wrong.
    request:
      url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/scrapeconfigs/:jobName"
      method: PUT
      params:
        - name: instanceId
          value: ""
          type: path
        - name: jobName
          value: ""
          type: path
        - name: projectId
          value: ""
          type: path
      body:
        type: json
        data: |-
          {
            "basicAuth": {
              "password": "",
              "username": ""
            },
            "bearerToken": "",
            "honorLabels": false,
            "honorTimeStamps": false,
            "metricsPath": "",
            "metricsRelabelConfigs": [
              {
                "action": "replace",
                "modulus": 0,
                "regex": "",
                "replacement": "",
                "separator": "",
                "sourceLabels": [],
                "targetLabel": ""
              }
            ],
            "params": {},
            "sampleLimit": 0,
            "scheme": "http",
            "scrapeInterval": "",
            "scrapeTimeout": "",
            "staticConfigs": [
              {
                "labels": {},
                "targets": []
              }
            ],
            "tlsConfig": {
              "insecureSkipVerify": false
            }
          }
    response:
      status: 400
      statusText: Bad Request
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "message": "Something went wrong"
          }
  - name: 403 Response
    description: You are not authorized
    request:
      url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/scrapeconfigs/:jobName"
      method: PUT
      params:
        - name: instanceId
          value: ""
          type: path
        - name: jobName
          value: ""
          type: path
        - name: projectId
          value: ""
          type: path
      body:
        type: json
        data: |-
          {
            "basicAuth": {
              "password": "",
              "username": ""
            },
            "bearerToken": "",
            "honorLabels": false,
            "honorTimeStamps": false,
            "metricsPath": "",
            "metricsRelabelConfigs": [
              {
                "action": "replace",
                "modulus": 0,
                "regex": "",
                "replacement": "",
                "separator": "",
                "sourceLabels": [],
                "targetLabel": ""
              }
            ],
            "params": {},
            "sampleLimit": 0,
            "scheme": "http",
            "scrapeInterval": "",
            "scrapeTimeout": "",
            "staticConfigs": [
              {
                "labels": {},
                "targets": []
              }
            ],
            "tlsConfig": {
              "insecureSkipVerify": false
            }
          }
    response:
      status: 403
      statusText: Forbidden
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "detail": "You do not have permission to perform this action."
          }
  - name: 404 Response
    description: Scrape target not found.
    request:
      url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/scrapeconfigs/:jobName"
      method: PUT
      params:
        - name: instanceId
          value: ""
          type: path
        - name: jobName
          value: ""
          type: path
        - name: projectId
          value: ""
          type: path
      body:
        type: json
        data: |-
          {
            "basicAuth": {
              "password": "",
              "username": ""
            },
            "bearerToken": "",
            "honorLabels": false,
            "honorTimeStamps": false,
            "metricsPath": "",
            "metricsRelabelConfigs": [
              {
                "action": "replace",
                "modulus": 0,
                "regex": "",
                "replacement": "",
                "separator": "",
                "sourceLabels": [],
                "targetLabel": ""
              }
            ],
            "params": {},
            "sampleLimit": 0,
            "scheme": "http",
            "scrapeInterval": "",
            "scrapeTimeout": "",
            "staticConfigs": [
              {
                "labels": {},
                "targets": []
              }
            ],
            "tlsConfig": {
              "insecureSkipVerify": false
            }
          }
    response:
      status: 404
      statusText: Not Found
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "message": "Scrape target not found."
          }

docs: Update scrape config.
