info:
  name: UpdateCredentialsRemoteWriteConfig
  type: http
  seq: 57

http:
  method: PUT
  url: "{{baseUrl}}/v1/projects/:projectId/instances/:instanceId/credentials/:username/remote-write-limits"
  params:
    - name: instanceId
      value: ""
      type: path
    - name: projectId
      value: ""
      type: path
    - name: username
      value: ""
      type: path
  body:
    type: json
    data: |-
      {
        "maxLimit": 0
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: Update remote write config for credentials.
