info:
  name: Get an admin kubeconfig for use with the STACKIT CLI
  type: http
  seq: 9

http:
  method: GET
  url: "{{baseUrl}}/v2/projects/:projectId/regions/:region/clusters/:clusterName/kubeconfig/login"
  params:
    - name: projectId
      value: ""
      type: path
    - name: region
      value: ""
      type: path
    - name: clusterName
      value: ""
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: A admin kubeconfig retrieved using this endpoint does not contain any credentials and instead obtains valid credentials via the STACKIT CLI.
