info:
  name: Get a kubeconfig to authenticate via IDP for use with the STACKIT CLI
  type: http
  seq: 8

http:
  method: GET
  url: "{{baseUrl}}/v2/projects/:projectId/regions/:region/clusters/:clusterName/kubeconfig/idp"
  params:
    - name: projectId
      value: ""
      type: path
    - name: region
      value: ""
      type: path
    - name: clusterName
      value: ""
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: A kubeconfig retrieved using this endpoint does not contain any credentials and instead obtains valid credentials via the STACKIT CLI. Permissions must be granted to the user beforehand using an admin kubeconfig.
