info:
  name: Check Manifest Existence
  type: http
  seq: 1
  tags:
    - Manifests

http:
  method: HEAD
  url: "{{baseUrl}}/v2/:namespace/:name/manifests/:reference"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: |
  Checks for the existence of an image manifest or image index.
  Returns the manifest's digest and content type in the headers if it exists.
